Update reusable-workflow.yml

diff --git a/.github/workflows/reusable-workflow.yml b/.github/workflows/reusable-workflow.yml
--- a/.github/workflows/reusable-workflow.yml
+++ b/.github/workflows/reusable-workflow.yml
@@ -12,5 +12,10 @@ jobs:
     steps:
       - env:
            URL: ${{ inputs.ingress-url }}
+           run: |
+             if [ -z "$URL" ]; then
+              echo "ERROR: URL is not set"
+              exit 1
+              fi
         run: |
           curl https://$URL/live -s -k | jq -r .status | grep -i live
